<?php
/**
 * Component categories and table mapping for PC Builder.
 * Used by admin (add/edit) and user (browse, builder).
 * default_image: real product-style image used when no image_url in DB (Unsplash, etc.).
 */
return [
    'cabinet' => [
        'label'   => 'Case',
        'table'   => 'cabinet',
        'id_col'  => 'model_name',
        'name_col'=> 'full_name',
        'price_col'=> 'price',
        'default_image' => 'https://images.unsplash.com/photo-1587202372775-e229f172b9d7?w=520&q=80',
        'has_socket' => false,
        'has_ram_type' => false,
        'has_wattage' => false,
        'has_form_factor' => false,
    ],
    'processor' => [
        'label'   => 'CPU',
        'table'   => 'processor',
        'id_col'  => 'cpu_id',
        'name_col'=> 'cpu_full_name',
        'price_col'=> 'price',
        'default_image' => 'https://images.unsplash.com/photo-1591799264318-7e6ef8ddb7ea?w=520&q=80',
        'has_socket' => true,
        'has_ram_type' => false,
        'has_wattage' => false,
        'has_form_factor' => false,
    ],
    'motherboard' => [
        'label'   => 'Motherboard',
        'table'   => 'motherboard',
        'id_col'  => 'mb_id',
        'name_col'=> 'mb_full_name',
        'price_col'=> 'price',
        'default_image' => 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=520&q=80',
        'has_socket' => true,
        'has_ram_type' => true,
        'has_wattage' => false,
        'has_form_factor' => true,
    ],
    'gpu' => [
        'label'   => 'GPU',
        'table'   => 'gpu',
        'id_col'  => 'gpu_id',
        'name_col'=> 'gpu_full_name',
        'price_col'=> 'price',
        'default_image' => 'https://images.unsplash.com/photo-1591488320449-011701bb6704?w=520&q=80',
        'has_socket' => false,
        'has_ram_type' => false,
        'has_wattage' => false,
        'has_form_factor' => false,
    ],
    'ram' => [
        'label'   => 'RAM',
        'table'   => 'ram',
        'id_col'  => 'ram_id',
        'name_col'=> 'ram_full_name',
        'price_col'=> 'price',
        'default_image' => 'https://images.unsplash.com/photo-1562976540-1502c2145186?w=520&q=80',
        'has_socket' => false,
        'has_ram_type' => true,
        'has_wattage' => false,
        'has_form_factor' => false,
    ],
    'ssd' => [
        'label'   => 'Storage (SSD)',
        'table'   => 'ssd',
        'id_col'  => 'ssd_id',
        'name_col'=> 'ssd_full_name',
        'price_col'=> 'price',
        'default_image' => 'https://images.unsplash.com/photo-1597872200969-2b65d565e384?w=520&q=80',
        'has_socket' => false,
        'has_ram_type' => false,
        'has_wattage' => false,
        'has_form_factor' => false,
    ],
    'hdd' => [
        'label'   => 'Storage (HDD)',
        'table'   => 'hdd',
        'id_col'  => 'hdd_id',
        'name_col'=> 'hdd_full_name',
        'price_col'=> 'price',
        'default_image' => 'https://images.unsplash.com/photo-1597872200969-2b65d565e384?w=520&q=80',
        'has_socket' => false,
        'has_ram_type' => false,
        'has_wattage' => false,
        'has_form_factor' => false,
    ],
    'power_supply' => [
        'label'   => 'PSU',
        'table'   => 'power_supply',
        'id_col'  => 'ps_id',
        'name_col'=> 'ps_full_name',
        'price_col'=> 'price',
        'default_image' => 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=520&q=80',
        'has_socket' => false,
        'has_ram_type' => false,
        'has_wattage' => true,
        'has_form_factor' => false,
    ],
    'cpu_cooler' => [
        'label'   => 'Cooling',
        'table'   => 'cpu_cooler',
        'id_col'  => 'cooler_id',
        'name_col'=> 'cooler_full_name',
        'price_col'=> 'price',
        'default_image' => 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=520&q=80',
        'has_socket' => false,
        'has_ram_type' => false,
        'has_wattage' => false,
        'has_form_factor' => false,
    ],
];
